name: build-test

on:
  push:
    paths:
      - 'microservices/hello-fastapi/**'
  pull_request:
    paths:
      - 'microservices/hello-fastapi/**'

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: microservices/hello-fastapi
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install fastapi uvicorn httpx pytest pytest-cov
      - name: Unit & integration tests
        run: pytest
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
