name: container-scan

on:
  workflow_run:
    workflows: ['build-test']
    types: [completed]

permissions:
  contents: read
  security-events: write

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t app:ci microservices/hello-fastapi
      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.27.0
        with:
          image-ref: app:ci
          format: sarif
          output: trivy-results.sarif
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
